import { NextPage } from "next";
import Head from "next/head";
import { useAuth } from "../context/auth";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const ctx = useAuth();
  const payload = {
    email: "ranganath.sahaayaadmin@gmail.com",
    password: "ssa@2021",
  };

  const login = async () => {
    console.log(ctx?.authenticateUser(payload))
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         <a href="#">Third Approach</a>
        </h1>
        <button onClick={login}>
          Login
        </button>
      </main>
    </div>
  );
};


export default Home