import Head from "next/head";
import { Button } from "semantic-ui-react";
import { useAuth } from "../context/AuthContext";
import styles from "../styles/Home.module.css";

const Home: React.FC = () => {
  const ctx = useAuth();
  const payload = {
    email: "ranganath.sahaayaadmin@gmail.com",
    password: "ssa@2021",
  };

  const login = async () => {
    console.log(ctx?.authenticateUser(payload))
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">My Site</a>
        </h1>
        <Button loading={ctx.isLoading} secondary onClick={login}>
          Login
        </Button>
      </main>
    </div>
  );
};

export default Home